#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Problem 29 from Project Euler

How many distinct terms are in the sequence generated by a^(b) for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
"""

m = 100
pl = []

for i in range(2, m+1):
    for j in range(2, m+1):
        pl.append(pow(i, j))

print len(sorted(set(pl)))
